#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "Please provide a directory to cache music files"
    exit 1
fi

if [ ! -d "$1" ]; then
    echo "$1 is not a directory!"
    exit 1
fi

pid="-1"

while true
do

    if ! ps --pid "$pid" &> /dev/null; then
        rand="$(shuf -i 1-198510 -n 1)"
        file="$1/$rand"
        if [ ! -f "$file" ]; then
            status="$(curl -s -o "$file" -w "%{http_code}" "https://modarchive.org/jsplayer.php?moduleid=$rand")"
            if [ "$status" != "200" ]; then
                continue
            fi 
        fi
        xmp "$file" &
        pid="$!"
    fi

    read -n 1 -s -r -t 1 cmd
    case "$cmd" in
        q)
            pkill --signal 9 -P "$$"
            exit 1
            ;;
        n)
            pkill --signal 9 -P "$$"
            pid="-1"
            ;;
    esac

done


